language: php
php:
  - '5.2'
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script: phpenv config-add myconfig.ini
script: php script/unit.script.php
matrix:
  allow_failures:
    - php: '5.6'
    - php: hhvm
    - php: '7.0'
    - php: nightly
  fast_finish: true
