build: false
shallow_clone: false
platform: 'x86'

install:
  - cinst -y php
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%

test_script:
  - cd C:\projects\task-manager
  - php script/unit.script.php
